version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge